In [258]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix
from collections import Counter
import operator

In [259]:
dataset=pd.read_csv("Abnormality.csv")

In [260]:
dataset

patient  features  features.1  features.2  features.3  features.4  \
0    abnormality1  0.193085    0.452288    0.415949    0.139162    0.193064   
1    abnormality2  0.455707    0.400769    0.232735    0.043859    0.171187   
2    abnormality3  0.216496    0.322787    0.321861    0.025466    0.351955   
3    abnormality4  0.103720    0.287073    0.297168    0.069759    0.341625   
4    abnormality5  0.180818    0.309175    0.204455    0.213910    0.257745   
..            ...       ...         ...         ...         ...         ...   
92  abnormality93  0.704218    0.441169    0.473228    0.160781    0.249248   
93  abnormality94  0.009908    0.610792    0.091674    0.013564    0.082230   
94  abnormality95  0.315815    0.438394    0.471392    0.050065    0.028890   
95  abnormality96  0.494521    0.387770    0.417113    0.240611    0.013166   
96  abnormality97  0.418626    0.462840    0.514597    0.049919    0.084683   

    features.5  features.6  features.7  features.8  ...  features.109  \
0     0.473900    0.453628    0.226506    0.486974  ...      0.325062   
1     0.397085    0.435364    0.198269    0.478201  ...      0.415000   
2     0.304562    0.190576    0.242715    0.059984  ...      0.588951   
3     0.322145    0.197875    0.327782    0.683889  ...      0.219669   
4     0.465277    0.274290    0.177519    0.218036  ...      0.199044   
..         ...         ...         ...         ...  ...           ...   
92    0.535597    0.228981    0.155537    0.402664  ...      0.424211   
93    0.333644    0.473475    0.330545    0.350644  ...      0.458550   
94    0.416679    0.320198    0.310576    0.477753  ...      0.004295   
95    0.513736    0.311139    0.270945    0.490570  ...      0.342005   
96    0.447421    0.177994    0.221872    0.573770  ...      0.776963   

    features.110  features.111  features.112  features.113  features.114  \
0       0.390048      0.068589      0.239278      0.325062      0.221802   
1       0.152374      0.009217      0.231085      0.415000      0.130759   
2       0.264538      0.233772      0.360888      0.588951      0.343463   
3       0.205674      0.121860      0.140276      0.219669      0.043324   
4       0.056704      0.122244      0.547757      0.199044      0.273875   
..           ...           ...           ...           ...           ...   
92      0.167415      0.164574      0.266798      0.424211      0.268330   
93      0.364114      0.124643      0.527569      0.458550      0.288735   
94      0.264463      0.205981      0.345524      0.004295      0.402601   
95      0.106542      0.058091      0.323474      0.342005      0.251820   
96      0.092422      0.184247      0.208823      0.776963      0.242964   

    features.115  features.116  features.117  class  
0       0.325062      0.112128      0.068589      1  
1       0.415000      0.085114      0.009217      1  
2       0.588951      0.207494      0.233772      1  
3       0.219669      0.016444      0.121860      0  
4       0.199044      0.468982      0.122244      1  
..           ...           ...           ...    ...  
92      0.424211      0.039538      0.164574      0  
93      0.458550      0.246396      0.124643      0  
94      0.004295      0.169348      0.205981      0  
95      0.342005      0.017518      0.058091      0  
96      0.776963      0.075716      0.184247      0  

[97 rows x 120 columns]

In [261]:
X=dataset.iloc[:,1:119]

In [262]:
X

features  features.1  features.2  features.3  features.4  features.5  \
0   0.193085    0.452288    0.415949    0.139162    0.193064    0.473900   
1   0.455707    0.400769    0.232735    0.043859    0.171187    0.397085   
2   0.216496    0.322787    0.321861    0.025466    0.351955    0.304562   
3   0.103720    0.287073    0.297168    0.069759    0.341625    0.322145   
4   0.180818    0.309175    0.204455    0.213910    0.257745    0.465277   
..       ...         ...         ...         ...         ...         ...   
92  0.704218    0.441169    0.473228    0.160781    0.249248    0.535597   
93  0.009908    0.610792    0.091674    0.013564    0.082230    0.333644   
94  0.315815    0.438394    0.471392    0.050065    0.028890    0.416679   
95  0.494521    0.387770    0.417113    0.240611    0.013166    0.513736   
96  0.418626    0.462840    0.514597    0.049919    0.084683    0.447421   

    features.6  features.7  features.8  features.9  ...  features.108  \
0     0.453628    0.226506    0.486974    0.202100  ...      0.190899   
1     0.435364    0.198269    0.478201    0.271058  ...      0.113019   
2     0.190576    0.242715    0.059984    0.194685  ...      0.212104   
3     0.197875    0.327782    0.683889    0.036612  ...      0.087971   
4     0.274290    0.177519    0.218036    0.122765  ...      0.230871   
..         ...         ...         ...         ...  ...           ...   
92    0.228981    0.155537    0.402664    0.362699  ...      0.232464   
93    0.473475    0.330545    0.350644    0.166074  ...      0.224257   
94    0.320198    0.310576    0.477753    0.288750  ...      0.315762   
95    0.311139    0.270945    0.490570    0.246249  ...      0.209006   
96    0.177994    0.221872    0.573770    0.400584  ...      0.239830   

    features.109  features.110  features.111  features.112  features.113  \
0       0.325062      0.390048      0.068589      0.239278      0.325062   
1       0.415000      0.152374      0.009217      0.231085      0.415000   
2       0.588951      0.264538      0.233772      0.360888      0.588951   
3       0.219669      0.205674      0.121860      0.140276      0.219669   
4       0.199044      0.056704      0.122244      0.547757      0.199044   
..           ...           ...           ...           ...           ...   
92      0.424211      0.167415      0.164574      0.266798      0.424211   
93      0.458550      0.364114      0.124643      0.527569      0.458550   
94      0.004295      0.264463      0.205981      0.345524      0.004295   
95      0.342005      0.106542      0.058091      0.323474      0.342005   
96      0.776963      0.092422      0.184247      0.208823      0.776963   

    features.114  features.115  features.116  features.117  
0       0.221802      0.325062      0.112128      0.068589  
1       0.130759      0.415000      0.085114      0.009217  
2       0.343463      0.588951      0.207494      0.233772  
3       0.043324      0.219669      0.016444      0.121860  
4       0.273875      0.199044      0.468982      0.122244  
..           ...           ...           ...           ...  
92      0.268330      0.424211      0.039538      0.164574  
93      0.288735      0.458550      0.246396      0.124643  
94      0.402601      0.004295      0.169348      0.205981  
95      0.251820      0.342005      0.017518      0.058091  
96      0.242964      0.776963      0.075716      0.184247  

[97 rows x 118 columns]

In [263]:
y=dataset.iloc[:,-1]

In [264]:
y

0     1
1     1
2     1
3     0
4     1
     ..
92    0
93    0
94    0
95    0
96    0
Name: class, Length: 97, dtype: int64

In [265]:
#Split dataset into training set and test set
x_train, x_test, y_train, y_test = train_test_split(X, y, train_size=0.6) 

In [266]:
xtrain=x_train.values

In [267]:
xtrain

array([[0.52741676, 0.29241878, 0.34979549, ..., 0.82040983, 0.223452  ,
        0.04971982],
       [0.31121072, 0.56066349, 0.06942164, ..., 0.7143163 , 0.28231556,
        0.35557375],
       [0.20265692, 0.70358667, 0.31685777, ..., 0.70084186, 0.22978615,
        0.12965251],
       ...,
       [0.27564978, 0.35726577, 0.22246609, ..., 0.3776512 , 0.14540507,
        0.4071785 ],
       [0.2431438 , 0.42935381, 0.26633408, ..., 0.3746745 , 0.12011716,
        0.34612931],
       [0.39845527, 0.70793207, 0.08041523, ..., 0.20767837, 0.25203219,
        0.50367757]])

In [268]:
#xtrain[1]#show only 2nd row

In [269]:
ytrain=y_train.values

In [270]:
ytrain

array([0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1], dtype=int64)

In [271]:
xtest=x_test.values


In [272]:
xtest

array([[0.10371984, 0.28707295, 0.29716807, ..., 0.21966943, 0.01644363,
        0.12186005],
       [0.38026511, 0.00228928, 0.35349828, ..., 0.04047016, 0.25709483,
        0.18951161],
       [0.2446843 , 0.36332675, 0.30303152, ..., 0.31322363, 0.17079072,
        0.44647228],
       ...,
       [0.64303723, 0.77139394, 0.26542629, ..., 0.27248199, 0.02215686,
        0.76176117],
       [0.3038548 , 0.55059362, 0.11218503, ..., 0.17770258, 0.36311539,
        0.35032615],
       [0.2430709 , 0.47926891, 0.03898752, ..., 0.27309851, 0.31636807,
        0.41722963]])

In [273]:
ytest=y_test.values

In [274]:
ytest

array([0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1], dtype=int64)

In [275]:
ytest.shape

(39,)

In [286]:

def euclidean_distance(x1, x2):
        return np.sqrt(np.sum((x1 - x2)**2))


class KNN:

    def __init__(self, k=k):
        self.k = k

    def fit(self, xt, yt):
        self.xtrain = xt
        self.ytrain = yt

    def predict(self, xtest):
        
        # list to store all our predictions
        predictions = []
        
        # loop over all observations in the test set
        for i in range(len(xtest)):            
            
            # calculate the distance between the test point and all other points in the training set
            dist = np.array([euclidean_distance(xtest[i], x_t) for x_t in self.xtrain])
            
            # sort the distances and return the indices of K neighbors
            dist_sorted = dist.argsort()[:self.k]
            
            # get the neighbors
            neigh_count = {}
 
            # for each neighbor find the class
            for idx in dist_sorted:
                if self.ytrain[idx] in neigh_count:
                    neigh_count[self.ytrain[idx]] += 1
                else:
                    neigh_count[self.ytrain[idx]] = 1
            
            sorted_neigh_count = sorted(neigh_count.items(), key=operator.itemgetter(1), reverse=True)
            
            # append the class label to the list
            predictions.append(sorted_neigh_count[0][0])
        return predictions

In [287]:
k = 5
clf = KNN(k=k)
clf.fit(xtrain, ytrain)
predictions = clf.predict(xtest)


In [288]:
print(predictions)

[0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]


In [289]:
#predictions.shape

In [290]:
print(classification_report(ytest, predictions))
print(confusion_matrix(ytest, predictions))

              precision    recall  f1-score   support

           0       0.74      0.86      0.79        29
           1       0.20      0.10      0.13        10

    accuracy                           0.67        39
   macro avg       0.47      0.48      0.46        39
weighted avg       0.60      0.67      0.62        39

[[25  4]
 [ 9  1]]
